server.port= 8091


#spring.datasource.url=jdbc:mysql://localhost:3306/user?characterEncoding=UTF-8
#spring.datasource.username=root
#spring.datasource.password=123456
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver

spring.druid.driverClassName = druid
spring.druid.driverClassName = com.mysql.jdbc.Driver
spring.druid.url = jdbc:mysql://127.0.0.1:3306/houses?useUnicode=true&amp;amp;characterEncoding=UTF-8&amp;amp;zeroDateTimeBehavior=convertToNull
spring.druid.username = root
spring.druid.password = root123
#\u6700\u5927\u8FDE\u63A5\u6570
spring.druid.maxActive = 30
#\u6700\u5C0F\u8FDE\u63A5\u6570
spring.druid.minIdle = 5
#\u83B7\u53D6\u8FDE\u63A5\u6700\u5927\u7B49\u5F85\u65F6\u95F4
spring.druid.maxWait = 10000
#\u89E3\u51B3mysql8\u5C0F\u65F6\u95EE\u9898,
spring.druid.validationQuery = SELECT 'x'
#\u7A7A\u95F2\u8FDE\u63A5\u68C0\u67E5\u95F4\u9694\u65F6\u95F4
spring.druid.timeBetweenEvictionRunsMillis = 60000
#\u7A7A\u95F2\u8FDE\u63A5\u6700\u5C0F\u7A7A\u95F2\u65F6\u95F4\uFF0C\u8FBE\u5230\u8FD9\u4E2A\u65F6\u95F4\u5C5E\u4E8E\u7A7A\u95F2\u8FDE\u63A5
spring.druid.minEvictableIdleTimeMillis = 300000